export const SETUP_WORKSTATIONS = 'SETUP_WORKSTATIONS';
export const SET_ITERATION_COUNT = 'SET_ITERATION_COUNT';
export const RUN_ITERATIONS = 'RUN_ITERATIONS';
export const RUN_TURNS = 'RUN_TURNS';
export const TIMER_START = 'TIMER_START';
export const TIMER_TRIGGER = 'TIMER_TRIGGER';
export const TIMER_STOP = 'TIMER_STOP';
