export const SETUP_WORKSTATIONS = 'SETUP_WORKSTATIONS';
export const SET_ITERATION_COUNT = 'SET_ITERATION_COUNT';
export const RUN_ITERATIONS = 'RUN_ITERATIONS';
export const RUN_TURNS = 'RUN_TURNS';
